In [1]:
print(1-2)
print(4*5)
print(7/5)
print(3**2)

-1
20
1.4
9


In [2]:
print(type(10))
print(type(2.718))
print(type("hello"))

<class 'int'>
<class 'float'>
<class 'str'>


In [4]:
x = 10
print(x)

x = 100
print(x)

y = 3.14
print(x*y)

print(type(x*y))

10
100
314.0
<class 'float'>


In [5]:
a = [1,2,3,4,5]
print(a)
print(len(a))
print(a[0])
print(a[4])

a[4] = 99
print(a)

[1, 2, 3, 4, 5]
5
1
5
[1, 2, 3, 4, 99]


In [7]:
print(a[0:2])
print(a[1:])
print(a[:3])
print(a[:-1])
print(a[:-2])

[1, 2]
[2, 3, 4, 99]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3]


In [9]:
me = {'height':180}
print(me['height'])

me['weight'] = 70
print(me)

180
{'height': 180, 'weight': 70}


In [10]:
hungry = True
sleepy = False

print(type(hungry))
print(not hungry)
print(hungry and sleepy)
print(hungry or sleepy)

<class 'bool'>
False
False
True


In [11]:
hungry = True
if hungry:
    print("I'm hungry")

hungry = False
if hungry:
    print("I'm hungry")
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm hungry
I'm not hungry
I'm sleepy


In [12]:
for i in[1,2,3]:
    print(i)

1
2
3


In [13]:
def hello():
    print("Hello World!")

hello()

Hello World!


In [15]:
def hello(object):
    print("Hello " + object + "!")

hello("cat")

Hello cat!


In [17]:
class Man:
    def __init__(self, name):
        self.name = name
        print("Initialized!")
    
    def hello(self):
        print("Hello " + self.name + "!")
    
    def goodbye(self):
        print("Good-bye " + self.name + "!")
    
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


In [19]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [20]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[0.5 0.5 0.5]


In [21]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

In [22]:
A = np.array([[1,2], [3,4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [23]:
B = np.array([[3,0], [0,6]])
print(A + B)
print(A * B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [24]:
print(A)
print(A*10)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [25]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])
A * B

array([[10, 40],
       [30, 80]])

In [26]:
X = np.array([[51, 55], [14,19], [0,4]])
print(X)
print(X[0])
print(X[0][1])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


In [27]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [28]:
X = X.flatten()
print(X)
X[np.array([0, 2, 4])]

[51 55 14 19  0  4]


array([51, 14,  0])

In [29]:
print(X>15)
print(X[X>15])

[ True  True False  True False False]
[51 55 19]
